#+TITLE: Mysteriousness -*- mode:org -*-
#+AUTHOR: Rick Neff
#+EMAIL:  NeffR@byui.edu
#+LANGUAGE:  en
#+OPTIONS:   H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t

* EN9

  You are invited to identify different algorithmic approaches to
  solving problems, and to compare and contrast these approaches using
  a variety of criteria. This invitation to exploration is codenamed
  /Mysteriousness/.

** Requirements

   Working with the members of your cohort only (no inter-cohort
   collaboration), using Brother Neff as your only other human
   resource, and using any non-human resources available to you,
   create algorithms to solve the following three problems:

*** Breaking Up Is Hard To Do

    Given two positive numbers A and B, where A is not equal to B,
    find a way to /break up/ the larger of the two numbers (call it A)
    into B unequal pieces. For example, if A = 34 and B = 4, then four
    unequal pieces of A are 6, 7, 9 and 12. These are unequal because
    there are no duplicate numbers. They break up (or sum up to) 34
    because 6 + 7 + 9 + 12 = 34. The numbers representing the pieces
    (e.g., 6, 7, 9 and 12) must be positive integers (1, 2, 3, etc.),
    which excludes zero.  Note that some pairs of numbers don't work,
    e.g., 5 and 3. Omit the uninteresting part of the algorithm, that
    is, the part that would enforce the assumption that A is larger
    than B.

*** What Is The Answer?

    In this new version of Scrabble ...

    - Letter values are all positive integers (zero not allowed).
    - Each vowel has a different numeric value.
    - Each consonant has a different numeric value.
    - A vowel can have the same value as a consonant.
    - Word scores are computed by adding up the vowel values, adding up the consonant values, and multiplying these two sums together.

    Given these word scores ...

    |       |   |     |   |   |         |   |    |   |   |       |   |     |
    | PLUM  | = |  36 |   |   | PLUME   | = | 48 |   |   | MELT  | = |  15 |
    | ROME  | = |  98 |   |   | SAVE    | = | 51 |   |   | WEST  | = |  20 |
    | LAME  | = |  18 |   |   | PLANE   | = | 39 |   |   | VIPER | = | 150 |
    | PIPER | = | 110 |   |   | OUT     | = | 81 |   |   | GREET | = |  40 |
    | MELBA | = |  51 |   |   | WESTERN | = | 70 |   |   | PAPER | = |  66 |

    ... what is the score of the following "word"?

#+BEGIN_CENTER
=PROBLEMSOLVING=
#+END_CENTER

*** What Is The Question?

    Whatever it is, it was inspired by the [[http://scriptures.lds.org/en/abr/fac_2][Book of Abraham, Facsimile No. 2, explanation of Figure 11]].

    /If the student can find out these numbers, so let it be .../

    | 8247830262 |
    | 7812996882 |
    | 1363377798 |
    | 1314834207 |
    | 2153753129 |
    | 6332798584 |
    | 4378329335 |
    | 8483580777 |
    | 9899336077 |
    | 3201725555 |

** Expectations

   You can write pseudocode or even real code if you wish, but the main
   product of this exploration is a report that describes at a high level
   each algorithm, especially how you and it solved these three problems.
   Include your analysis of each approach and a discussion of the various
   criteria you discovered /or created/ by which to evaluate each approach.

   You are expected to write a good introduction (stating the goal of
   this activity) and conclusion (summarizing your analysis), and use
   correct grammar and spelling throughout.

   You are also expected to use *org mode* to write your report.

** Questions

*** Problem 3

    I will do my best to imitate Dr. Lanning's hologram program:

    A "Type 1" (abbreviated by holding up 1 finger) question elicits
    the response: "I'm sorry, my responses are limited. You must ask
    the right TYPE of question."

    - Are those numbers supposed to be inputs to be consumed or are they outputs to be produced?
    - What type of data are we looking at producing?
    - Is the entire number significant, or is each digit significant?
    - Are they different numbers or one long number?
    - Have we experimented with this before?
    - If so, what was it?
    - If not, why not?
    - How does elisp help us solve this problem?
    - What is the outcome for students Brother Neff is looking for?
    - Is it possible that there is no efficient way of finding the solution,
      except for asking Brother Neff what the solution is?
    - What is the algorithmic complexity of the algorithm?
    - Once we know that our questions are of Type 2, how do we find their answers?
    - Is the algorithm based on the Book of Abraham Facsimile #2 in any way, or something else?
      
    A "Type 2" (2 fingers) question elicits the response: "That, dear
    student (detective), is the right TYPE of question."

    - Is it a matrix?
    - Is it safe to assume these numbers are in base 10?
    - Is there only one correct answer?
    - Is there something we can use to check to see if we have the right answer?
    - Do you have to do arithmetic with these numbers?
    - Is there a topological ordering to the numbers?
    - Was the function that generated the numbers one-way?
    - Does Brother Neff enjoy making his students think?
    - Does this question get solved all the time?
    - Is there another source that would assist us in solving this?
    - Is this question at all related to the previous questions?
    - Is Brother Neff actually going to answer any of these questions?
    - Does the process to solve this problem have any relation to something specific in discrete math?
    - Is the output of our algorithm to be a question?
    - Would Brother Neff call the solution method a meta-algorithm?
    - Does the solution require a Godel-Escher-Bach-style algorithm?
    - Is the output human readable?
    - Are there more than just Type 1 or Type 2 questions?

    A Type 3 question elicits the response: "That, dear student (detective), is THE RIGHT question. Program terminated."

**** Hints:

  The question has exactly twenty words, all unique (no repeats).

  No word has more than two syllables.

  There are no "uncommon" words
  (see http://firstthreeodds.org/cs306/commonWords.txt for a list of 2300 common words).

  Half of the words have 4 letters, and of the remaining 10, 7 have 3
  or fewer, and 3 have 5 or more.

  | Number of letters | Number of words having that number of letters |
  |-------------------+-----------------------------------------------|
  |                 1 | 1                                             |
  |                 2 | 3                                             |
  |                 3 | 3                                             |
  |                 4 | 10                                            |
  |                 5 | 1                                             |
  |                 6 | 1                                             |
  |                 7 | 1                                             |

** What is True?

#+BEGIN_SRC emacs-lisp
(defun what-is-true-about-my-engagement-with-mysteriousness ()
  "If need be, replace a 100 with a smaller number to reflect how much you feel you deserve."
  (vector
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true of my experience in general?                              ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["I had fun." 100]
["I collaborated with the classmates in my cohort." 100]
["I learned something new." 100]
["I achieved something meaningful, or something I can build upon at a later time." 100]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true of my report on what I learned?                            ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["I learned the basics of emacs 'org' mode in order to write it." 100]
["I learned through writing it how to write a little better." 100]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true of the mechanical "infelicities" (misspelled words,        ;;
;; grammatical errors, punctuation errors) in my report on what I learned? ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["There are fewer than four." 100]
["There are fewer than three." 100]
["There are fewer than two." 100]
["There are none." 100]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is otherwise true of the quality of the information in my report?  ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["Each detail contributes to the report's purpose, with no distracting, extraneous information." 100]
["There are no unstated assumptions, and the arguments are logical and concise." 100]
["As confirmed by having someone not in my cohort read it, the reader can readily see what is going on in my head." 100]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is otherwise true of the organization of my report?                ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["My report's information is presented in a logical sequence, easily followed." 100]
["My report has a strong introduction, clearly stating the goal of this exploration." 100]
["My report has a strong conclusion, summarizing my analysis." 100]
["My report has pithy headings to guide the information flow." 100]
["The information flow in my report has engaging transitions that entice the reader to read further." 100]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true about my meeting explicit requirements?                    ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["I discussed my algorithms only at a high level, avoiding tedious descriptions of their details." 100]
["I discovered/created/reported on one explicit compare/contrast criterion for Problem 1." 100]
["I discovered/created/reported on two explicit compare/contrast criteria for Problem 1." 100]
["I discovered/created/reported on three explicit compare/contrast criteria for Problem 1." 100]
["I discovered/created/reported on one explicit compare/contrast criterion for Problem 2." 100]
["I discovered/created/reported on two explicit compare/contrast criteria for Problem 2." 100]
["I discovered/created/reported on three explicit compare/contrast criteria for Problem 2." 100]
["I discovered/created/reported on one explicit compare/contrast criterion for Problem 3." 100]
["I discovered/created/reported on two explicit compare/contrast criteria for Problem 3." 100]
["I discovered/created/reported on three explicit compare/contrast criteria for Problem 3." 100]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; On page 103 of his book /The Sense of Style/, Steven Pinker said:        ;;
;;                                                                          ;;
;; As with any form of mental self-improvement, you must learn to turn      ;;
;; your gaze inward, concentrate on processes that usually run              ;;
;; automatically, and try to wrest control of them so that you can apply    ;;
;; them more mindfully.                                                     ;;
;;                                                                          ;;
;; What is true about the introspection I did in coming up with algorithmic ;;
;; solutions to these problems, especially the third?                       ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["For Problem 1, I learned to apply more mindfully mental processes that usually run automatically." 100]
["For Problem 1, I supplied ample evidence of my introspection." 100]
["For Problem 2, I learned to apply more mindfully mental processes that usually run automatically." 100]
["For Problem 2, I supplied ample evidence of my introspection." 100]
["For Problem 3, I learned to apply more mindfully mental processes that usually run automatically." 100]
["For Problem 3, I supplied ample evidence of my introspection by discussing metacognitive miscalibration, and the orders of ignorance." 100]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; As quoted in J. Hartmanis /On computational complexity and the nature     ;;
;; of computer science/ published in the /Communications of the ACM 37/,     ;;
;; 10 (1994), 39, Donald Knuth said:                                         ;;
;;                                                                           ;;
;; Computer Science and Engineering is a field that attracts a different     ;;
;; kind of thinker. I believe that one who is a natural computer             ;;
;; scientist thinks algorithmically. Such people are especially good at      ;;
;; dealing with situations where different rules apply in different          ;;
;; cases; they are individuals who can rapidly change levels of abstraction, ;;
;; simultaneously seeing things "in the large" and "in the small."           ;;
;;                                                                           ;;
;; What is true about my algorithmic thinking, or aspirations thereto?       ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

["I discussed to what extent I am or desire to get good at dealing with situations where different rules apply in different cases." 100]
["I discussed to what extent I am or desire to be able to rapidly change levels of abstraction." 100]
["I discussed to what extent I can or desire to simultaneously see things in the large and in the small." 100]

))
#+END_SRC
